### PR TITLE
ReadMe: fix link to elle

### PR DESCRIPTION
**Pull request by kiney**

### CODE REVIEW

**Comment by kiney** [comment]
@Dimrok @akimd can you merge this? It's just a small typo fix...

**Comment by Dimrok** [comment]
Hi @kiney.

Yes sorry I didn't see the PR, I'll merge it today.

Thanks.

**Comment by kiney** [comment]
Hi @Dimrok,
just a gentle reminder, as I guess you forgot ;-)

**Comment by Dimrok** [comment]
Hi! Sorry memo is now back on track. PR accepted (91ddb20dba00f1cfbb31337bead0a5cf1f6a997c).

Thank you.

**Pull request merged**
